### ISSUE TITLE
Tool categories

### ISSUE THREAD

**Issue by craigsapp** [humdrum-tools/humdrum-documentation#1]
The main page for the tools now has a list of the command names and brief descriptions of the tool:
   
 https://www2.humdrum.org/tool

This list is generated from the file:

https://github.com/humdrum-tools/newdoc/blob/master/_data/tools.yml

For each tool, there is an entry like:

```yml
        - name: "assemble"
          description: "combine parts in two or more Humdrum files"
          tags: 
                - "Humdrum Toolkit"
                - "data processing"
```

The *tags* entries are lists of categories that each tool belongs to.   These tags are used to create the category selection list on the tools page:

<img width="465" alt="Screen Shot 2020-03-31 at 23 16 22" src="https://user-images.githubusercontent.com/3487289/78105703-a3514880-73a6-11ea-83be-621952db45b7.png">

@shanahdt should go through the list of commands adding additional tags as necessary.

@craigsapp will add Humdrum Extras tools to the list, as well as tools available as VHV filters.
