### ISSUE TITLE
Example 25.1 in User Guide has small text

### ISSUE THREAD

**Issue by craigsapp** [humdrum-tools/humdrum-documentation#3]
Example 25.1 in the User Guide has small text that needs to be made larger somehow.

**Comment by craigsapp** [comment]
The problem is that the font size was being set for all elements with this CSS selector:

```css
* {
        font-family: 'Alegreya Sans', sans-serif;
        font-size: 2.5rem;
        line-height: 3.0rem;
}
```

But the `font-size` was causing problems because the SVG fonts are very large (such as 405px).  Removing a default size fixes the problem:

```css
* {
        font-family: 'Alegreya Sans', sans-serif;
        /* font-size: 2.5rem; */
        line-height: 3.0rem;
}
```

Now the text is visible:

<img width="631" alt="Screen Shot 2020-04-13 at 08 06 24" src="https://user-images.githubusercontent.com/3487289/79131616-b6c4c200-7d5d-11ea-8226-e4fb7c2f98a4.png">
